anchors:
  aspect_ratios:
  - 1.0
  generator: AnchorGeneratorV2
  num_anchors: 1
  octave_base_scale: 8
  scales_per_octave: 1
  strides:
  - 8
  - 16
  - 32
  - 64
  - 128
backbone:
  activation:
    activation: relu
  backbone: ResNet101
  dilation_rates:
  - 1
  - 1
  - 1
  - 1
  - 1
  dropblock: null
  frozen_stages:
  - -1
  normalization:
    epsilon: 0.0001
    momentum: 0.997
    normalization: batch_norm
    trainable: false
  output_indices:
  - 3
  - 4
  - 5
  strides:
  - 2
  - 2
  - 2
  - 2
  - 2
data_format: channels_last
detector: ATSS
dtype: float32
excluding_weight_names:
- predicted_box
- predicted_class
- predicted_centerness
head:
  activation:
    activation: relu
  assigner:
    assigner: ATSSAssigner
    topk: 9
  bbox_decoder:
    decoder: Delta2Box
    weights:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
  bbox_encoder:
    encoder: Box2Delta
    weights:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
  bbox_loss:
    loss: GIoULoss
    reduction: sum
    weight: 2.0
  centerness_loss:
    from_logits: true
    loss: BinaryCrossEntropy
    reduction: sum
    weight: 1.0
  convolution: conv2d
  dropblock: null
  feat_dims: 256
  head: ATSSHead
  label_loss:
    alpha: 0.25
    from_logits: true
    gamma: 2.0
    label_smoothing: 0.0
    loss: FocalLoss
    reduction: sum
    weight: 1.0
  max_level: 7
  min_level: 3
  normalization:
    groups: 32
    normalization: group_norm
  num_classes: 80
  prior: 0.01
  repeats: 4
  sampler:
    sampler: PseudoSampler
  use_sigmoid: true
input_shape: !!python/tuple
- 1024
- 1024
- 3
neck:
  add_extra_convs: true
  feat_dims: 256
  max_level: 5
  min_level: 3
  neck: FPN
  num_output_levels: 5
  relu_before_extra_convs: true
num_classes: 80
test:
  iou_threshold: 0.6
  nms: CombinedNonMaxSuppression
  nms_type: nms
  post_nms_size: 100
  pre_nms_size: 1000
  score_threshold: 0.35
train:
  checkpoint_dir: checkpoints/atss
  dataset:
    augmentations:
    - augmentation: FlipLeftToRight
      probability: 0.5
    - augmentation: RandomDistortColor
    - augmentation: Resize
      img_scale: !!python/tuple
      - 0.2
      - 2
      keep_ratio: true
      multiscale_mode: range
    - augmentation: Pad
      size_divisor: 32
    batch_size: 4
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    num_classes: 80
    num_samples: 118287
    training: true
  gradient_clip_norm: 0.0
  log_every_n_steps: 100
  mixed_precision:
    loss_scale: null
  optimizer:
    momentum: 0.9
    optimizer: SGD
  pretrained_weights_path: /data/bail/pretrained_weights/resnet50/resnet50.ckpt
  save_ckpt_steps: 5000
  scheduler:
    learning_rate_scheduler:
      initial_learning_rate: 0.02
      scheduler: CosineDecay
    train_epochs: 36
    warmup:
      steps: 800
      warmup_learning_rate: 0.001
  summary_dir: logs/atss
val:
  dataset:
    augmentations:
    - augmentation: Resize
      img_scale:
      - !!python/tuple
        - 1333
        - !!python/tuple
          - 1024
          - 1024
      keep_ratio: true
    batch_size: 4
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    training: false
  samples: 5000
weight_decay: 0.0001
