anchors:
  aspect_ratios:
  - 1.0
  generator: AnchorGeneratorV2
  num_anchors: 1
  octave_base_scale: 8
  scales_per_octave: 1
  strides:
  - 8
  - 16
  - 32
  - 64
  - 128
backbone:
  activation:
    activation: relu
  backbone: ResNet50
  dilation_rates:
  - 1
  - 1
  - 1
  - 1
  - 1
  dropblock: null
  frozen_stages:
  - 1
  normalization:
    epsilon: 0.0001
    momentum: 0.997
    normalization: batch_norm
    trainable: false
  output_indices:
  - 3
  - 4
  - 5
  strides:
  - 2
  - 2
  - 2
  - 2
  - 2
data_format: channels_last
detector: GFL
dtype: float16
excluding_weight_names:
- predicted_box
- predicted_class
head:
  activation:
    activation: relu
  assigner:
    assigner: ATSSAssigner
    topk: 9
  bbox_decoder:
    decoder: Distance2Box
    weights: null
  bbox_encoder:
    encoder: Box2Distance
    weights: null
  bbox_loss:
    loss: GIoULoss
    reduction: sum
    weight: 2.0
  dfl_loss:
    loss: DistributionFocalLoss
    reduction: sum
    weight: 0.25
  dropblock: null
  feat_dims: 256
  head: GFLHead
  label_loss:
    beta: 2.0
    from_logits: true
    loss: QualityFocalLoss
    reduction: sum
    weight: 1.0
  max_level: 7
  min_level: 3
  normalization:
    groups: 32
    normalization: group_norm
  num_classes: 80
  prior: 0.01
  reg_max: 16
  repeats: 4
  sampler:
    sampler: PseudoSampler
  use_sigmoid: true
input_shape: !!python/tuple
- 1024
- 1024
- 3
neck:
  add_extra_convs: true
  feat_dims: 256
  max_level: 5
  min_level: 3
  neck: FPN
  num_output_levels: 5
  relu_before_extra_convs: true
num_classes: 80
test:
  iou_threshold: 0.6
  nms: CombinedNonMaxSuppression
  post_nms_size: 100
  pre_nms_size: 5000
  score_threshold: 0.3
train:
  checkpoint_dir: checkpoints/gfl
  dataset:
    augmentations:
    - augmentation: FlipLeftToRight
      probability: 0.5
    - augmentation: RandomDistortColor
    - augmentation: Resize
      img_scale:
      - &id001 !!python/tuple
        - 1333
        - 800
      keep_ratio: true
    - augmentation: Pad
      size_divisor: 32
    batch_size: 4
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    num_samples: 118287
    training: true
  gradient_clip_norm: 10.0
  log_every_n_steps: 100
  mixed_precision:
    loss_scale: null
  optimizer:
    momentum: 0.9
    optimizer: SGD
  pretrained_weights_path: /data/bail/pretrained_weights/resnet50/resnet50.ckpt
  save_ckpt_steps: 5000
  scheduler:
    learning_rate_scheduler:
      boundaries:
      - 16
      - 22
      scheduler: PiecewiseConstantDecay
      values:
      - 0.02
      - 0.002
      - 0.0002
    train_epochs: 24
    warmup:
      steps: 800
      warmup_learning_rate: 0.001
  summary_dir: logs/gfl
val:
  dataset:
    augmentations:
    - augmentation: Resize
      img_scale:
      - *id001
      keep_ratio: true
    - augmentation: Pad
      size_divisor: 32
    batch_size: 4
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    training: false
  samples: 5000
weight_decay: 0.0001
