anchor_threshold: 4.0
anchors:
- - 10
  - 13
  - 16
  - 30
  - 33
  - 23
- - 30
  - 61
  - 62
  - 45
  - 59
  - 119
- - 116
  - 90
  - 156
  - 198
  - 373
  - 326
balance:
- 4.0
- 1.0
- 0.4
bbox_loss:
  loss: CIoULoss
  reduction: sum
  weight: 0.05
conf_loss:
  from_logits: true
  loss: BinaryCrossEntropy
  reduction: sum
  weight: 1.0
depth_multiple: 0.33
detector: YOLOv5
dtype: float32
gr: 1.0
label_loss:
  from_logits: true
  loss: BinaryCrossEntropy
  reduction: sum
  weight: 0.5
max_level: 5
min_level: 3
model:
- - -1
  - 1
  - Focus
  - filters: 64
    kernel_size: 3
- - -1
  - 1
  - Conv
  - filters: 128
    kernel_size: 3
    strides: 2
- - -1
  - 3
  - BottleneckCSP
  - filters: 128
- - -1
  - 1
  - Conv
  - filters: 256
    kernel_size: 3
    strides: 2
- - -1
  - 9
  - BottleneckCSP
  - filters: 256
- - -1
  - 1
  - Conv
  - filters: 512
    kernel_size: 3
    strides: 2
- - -1
  - 9
  - BottleneckCSP
  - filters: 512
- - -1
  - 1
  - Conv
  - filters: 1024
    kernel_size: 3
    strides: 2
- - -1
  - 1
  - SpatialPyramidPooling
  - filters: 1024
    pool_sizes:
    - 5
    - 9
    - 13
- - -1
  - 3
  - BottleneckCSP
  - filters: 1024
    shortcut: false
- - -1
  - 1
  - Conv
  - filters: 512
    kernel_size: 1
    strides: 1
- - -1
  - 1
  - Upsample
  - interpolation: nearest
    size: 2
- - - -1
    - 6
  - 1
  - Concat
  - axis: -1
- - -1
  - 3
  - BottleneckCSP
  - filters: 512
    shortcut: false
- - -1
  - 1
  - Conv
  - filters: 256
    kernel_size: 1
    strides: 1
- - -1
  - 1
  - Upsample
  - interpolation: nearest
    size: 2
- - - -1
    - 4
  - 1
  - Concat
  - axis: -1
- - -1
  - 3
  - BottleneckCSP
  - filters: 256
    shortcut: false
- - -1
  - 1
  - Conv
  - filters: 256
    kernel_size: 3
    strides: 2
- - - -1
    - 14
  - 1
  - Concat
  - axis: -1
- - -1
  - 3
  - BottleneckCSP
  - filters: 512
    shortcut: false
- - -1
  - 1
  - Conv
  - filters: 512
    kernel_size: 3
    strides: 2
- - - -1
    - 10
  - 1
  - Concat
  - axis: -1
- - -1
  - 3
  - BottleneckCSP
  - filters: 1024
    shortcut: false
- - - 17
    - 20
    - 23
  - 1
  - Detect
  - anchors: anchors
    num_classes: num_classes
num_anchors: 3
num_classes: 80
strides:
- 8
- 16
- 32
test:
  iou_threshold: 0.6
  nms: NonMaxSuppressionWithQuality
  nms_type: nms
  post_nms_size: 100
  pre_nms_size: 2000
  score_threshold: 0.35
  sigma: 0.5
train:
  checkpoint_dir: checkpoints/yolov5s
  dataset:
    augmentations:
    - FlipLeftToRight:
        probability: 0.5
    - RandomDistortColor:
        probability: 1.0
    - Resize:
        max_scale: 2.0
        min_scale: 0.5
        size: &id001 !!python/tuple
        - 640
        - 640
        strides: 32
    batch_size: 8
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    num_classes: 80
    num_samples: 118287
    training: true
  gradient_clip_norm: 0.0
  input_size: *id001
  log_every_n_steps: 100
  mixed_precision:
    loss_scale: null
  optimizer:
    momentum: 0.9
    optimizer: SGD
  pretrained_weights_path: /data/bail/pretrained_weights/darknet53-notop/darknet53.ckpt
  save_ckpt_steps: 10000
  scheduler:
    learning_rate_scheduler:
      initial_learning_rate: 0.02
      scheduler: CosineDecay
    train_epochs: 40
    warmup:
      steps: 12000
      warmup_learning_rate: 0.0002
  summary_dir: logs/yolov5s
val:
  dataset:
    augmentations:
    - Resize:
        max_scale: 1.0
        min_scale: 1.0
        size: *id001
        strides: 32
    batch_size: 8
    dataset: COCODataset
    dataset_dir: /data/bail/COCO
    training: false
  input_size: *id001
  samples: 5000
weight_decay: 0.0001
width_multiple: 0.50
